TOPIC = dict(
    id="home-6", cat="home", catZh="居家", catEn="Around the House",
    title="臥室", titleEn="In a bedroom", emoji="🛏️",
    words=[
        ("alarm clock", "鬧鐘", "n.", "⏰", "My alarm clock rings at six thirty.", "我的鬧鐘在六點半響。"),
        ("picture frame", "相框", "n.", "🖼️", "There is a picture frame on my desk.", "我的書桌上有一個相框。"),
        ("lamp", "檯燈", "n.", "💡", "Turn off the lamp before you sleep.", "睡覺前把檯燈關掉。"),
        ("headboard cabinet", "床頭櫃（床頭置物櫃）", "n.", "🗄️", "I keep my glasses in the headboard cabinet.", "我把眼鏡放在床頭櫃裡。"),
        ("nightstand", "床邊小桌", "n.", "🪑", "A glass of water is on the nightstand.", "床邊小桌上有一杯水。"),
        ("pillow", "枕頭", "n.", "🛌", "This pillow is soft and comfortable.", "這個枕頭又軟又舒服。"),
        ("mattress", "床墊", "n.", "🛏️", "The new mattress is very firm.", "新床墊很硬挺。"),
        ("bedsheet", "床單", "n.", "🛏️", "Mom changes the bedsheet every week.", "媽媽每個星期換一次床單。"),
        ("comforter", "厚被子（羽絨被）", "n.", "🛌", "I need a thick comforter in winter.", "冬天我需要一條厚被子。"),
        ("chest of drawers", "五斗櫃", "n.", "🗄️", "My shirts are in the chest of drawers.", "我的襯衫放在五斗櫃裡。"),
        ("bookends", "書擋", "n.", "📚", "Use bookends to keep the books standing.", "用書擋讓書立在桌上。"),
        ("wardrobe", "衣櫥", "n.", "🚪", "Her dresses are hanging in the wardrobe.", "她的洋裝掛在衣櫥裡。"),
        ("cosmetics", "化妝品", "n.", "💄", "She keeps her cosmetics in a small bag.", "她把化妝品放在一個小袋子裡。"),
        ("vanity table", "梳妝台", "n.", "🪞", "She sits at the vanity table and brushes her hair.", "她坐在梳妝台前梳頭髮。"),
        ("footstool", "腳凳", "n.", "🪑", "Put your feet on the footstool.", "把腳放在腳凳上。"),
        ("undershirt", "內衣（貼身背心）", "n.", "👕", "He wears an undershirt under his shirt.", "他在襯衫裡面穿一件貼身背心。"),
        ("slippers", "拖鞋", "n.", "🥿", "Put on your slippers. The floor is cold.", "穿上拖鞋，地板很冰。"),
    ],
    speakers=dict(
        M=dict(name="Grace", zh="葛蕾絲", avatar="🙋‍♀️", voice="af_sarah"),
        B=dict(name="Leo", zh="里歐", avatar="🙋‍♂️", voice="am_michael"),
    ),
    dialogueTitle="換新房間：布置我的臥室",
    dialogue=[
        ("B", "Grace, your new bedroom looks great!", "葛蕾絲，你的新臥室看起來好棒！"),
        ("M", "Thanks. Dad helped me carry the mattress and the chest of drawers.", "謝謝。爸爸幫我搬了床墊和五斗櫃。"),
        ("B", "I like the nightstand next to the bed. Is that an alarm clock on it?", "我喜歡床邊的小桌。上面是鬧鐘嗎？"),
        ("M", "Yes, and there's a lamp and a picture frame, too.", "對，還有檯燈和相框。"),
        ("B", "Whose photo is in the picture frame?", "相框裡是誰的照片？"),
        ("M", "It's my family. I put it where I can see it every morning.", "是我的家人。我把它放在每天早上都看得到的地方。"),
        ("B", "Where do you keep your clothes?", "你的衣服放在哪裡？"),
        ("M", "My dresses are in the wardrobe, and my undershirts are in the chest of drawers.", "洋裝在衣櫥裡，貼身背心在五斗櫃裡。"),
        ("B", "Wow, your vanity table is so pretty. Are those your cosmetics?", "哇，你的梳妝台好漂亮。那些是你的化妝品嗎？"),
        ("M", "No, they're Mom's. I only put my books between the bookends.", "不是，那是媽媽的。我只把書放在書擋中間。"),
        ("B", "Is the comforter warm enough? It's cold at night.", "被子夠暖嗎？晚上很冷。"),
        ("M", "Yes, with a new bedsheet and a soft pillow. I have slippers and a footstool for reading, too.", "夠暖，還有新床單和軟枕頭。我也有拖鞋和腳凳可以看書用。"),
    ],
)
