TOPIC = dict(
    id="home-8", cat="home", catZh="居家", catEn="Around the House",
    title="廚房", titleEn="In a kitchen", emoji="🍳",
    words=[
        ("refrigerator", "冰箱", "n.", "🧊", "There is some milk in the refrigerator.", "冰箱裡有一些牛奶。"),
        ("apron", "圍裙", "n.", "👩‍🍳", "Put on an apron before you cook.", "煮飯前先穿上圍裙。"),
        ("mop", "拖把", "n.", "🧽", "Use a mop to clean the kitchen floor.", "用拖把清潔廚房地板。"),
        ("broom", "掃把", "n.", "🧹", "He sweeps the floor with a broom.", "他用掃把掃地。"),
        ("dust pan", "畚箕", "n.", "🧹", "Sweep the dirt into the dust pan.", "把灰塵掃進畚箕裡。"),
        ("range fan", "抽油煙機", "n.", "🌀", "Turn on the range fan when you fry fish.", "煎魚的時候要開抽油煙機。"),
        ("cupboard", "碗櫃", "n.", "🚪", "The plates are in the cupboard.", "盤子放在碗櫃裡。"),
        ("microwave oven", "微波爐", "n.", "📟", "Heat the soup in the microwave oven.", "用微波爐加熱湯。"),
        ("dish rack", "碗盤瀝水架", "n.", "🍽️", "Put the wet bowls on the dish rack.", "把濕碗放在瀝水架上。"),
        ("ladle", "湯勺", "n.", "🥄", "Use a ladle to serve the soup.", "用湯勺盛湯。"),
        ("cleaver", "菜刀（切大塊用的）", "n.", "🔪", "The cook cuts the meat with a cleaver.", "廚師用菜刀切肉。"),
        ("pan", "平底鍋", "n.", "🍳", "Fry the eggs in a pan.", "用平底鍋煎蛋。"),
        ("wok", "炒菜鍋", "n.", "🥘", "Stir-fry the vegetables in a wok.", "用炒菜鍋炒青菜。"),
        ("gas stove", "瓦斯爐", "n.", "🔥", "Turn off the gas stove after cooking.", "煮完飯後要關瓦斯爐。"),
        ("sink", "水槽", "n.", "🚰", "The dishes are in the sink.", "碗盤在水槽裡。"),
        ("counter", "流理台", "n.", "🍽️", "Put the vegetables on the counter.", "把蔬菜放在流理台上。"),
        ("cutting board", "砧板", "n.", "🪵", "Cut the tomatoes on the cutting board.", "在砧板上切番茄。"),
        ("oven", "烤箱", "n.", "♨️", "The cake is in the oven.", "蛋糕在烤箱裡。"),
        ("cabinet", "櫥櫃", "n.", "🗄️", "The cups are in the top cabinet.", "杯子放在最上面的櫥櫃。"),
        ("blender", "果汁機", "n.", "🥤", "Make a smoothie in the blender.", "用果汁機做冰沙。"),
        ("rice cooker", "電鍋（電子鍋）", "n.", "🍚", "The rice cooker is on the counter.", "電鍋放在流理台上。"),
        ("toaster", "烤麵包機", "n.", "🍞", "The toast popped out of the toaster.", "吐司從烤麵包機彈出來。"),
    ],
    speakers=dict(
        M=dict(name="Kevin", zh="凱文", avatar="🙋‍♂️", voice="am_michael"),
        B=dict(name="Aunt Lu", zh="盧阿姨", avatar="👩", voice="af_heart"),
    ),
    dialogueTitle="假日早午餐：阿姨教我做菜",
    dialogue=[
        ("B", "Kevin, put on an apron. Today we are making brunch.", "凱文，穿上圍裙，今天我們要做早午餐。"),
        ("M", "Great! What should I do first?", "太好了！我要先做什麼？"),
        ("B", "Take the eggs and milk out of the refrigerator, please.", "請把蛋和牛奶從冰箱拿出來。"),
        ("M", "Okay. Where are the pan and the wok?", "好。平底鍋和炒菜鍋在哪裡？"),
        ("B", "They're in the cabinet under the counter. Use the pan for the eggs.", "在流理台下面的櫥櫃裡，煎蛋用平底鍋。"),
        ("M", "Should I turn on the gas stove and the range fan?", "我要開瓦斯爐和抽油煙機嗎？"),
        ("B", "Yes, both. I'll cut the vegetables on the cutting board with a cleaver.", "對，兩個都要開。我來在砧板上用菜刀切菜。"),
        ("M", "Can I use the toaster for the bread?", "我可以用烤麵包機烤麵包嗎？"),
        ("B", "Sure. And put the soup in the microwave oven for two minutes.", "可以。還有，把湯放進微波爐加熱兩分鐘。"),
        ("M", "Done. The rice cooker is ready, too. Where is the ladle?", "好了。電鍋也好了。湯勺在哪裡？"),
        ("B", "On the dish rack. After we eat, you wash the dishes in the sink.", "在瀝水架上。吃完之後你要在水槽洗碗。"),
        ("M", "No problem. Then I'll take the broom, the dust pan, and the mop to clean the floor.", "沒問題。然後我會拿掃把、畚箕和拖把把地板弄乾淨。"),
    ],
)
