TOPIC = dict(
    id="home-5", cat="home", catZh="居家", catEn="Around the House",
    title="盥洗與個人用品", titleEn="Toiletries", emoji="🧴",
    words=[
        ("razor", "刮鬍刀", "n.", "🪒", "Dad uses a razor every morning.", "爸爸每天早上都用刮鬍刀。"),
        ("lipstick", "口紅", "n.", "💄", "She put on some red lipstick.", "她擦了一點紅色口紅。"),
        ("soap", "肥皂", "n.", "🧼", "Wash your hands with soap.", "用肥皂洗手。"),
        ("blow dryer", "吹風機", "n.", "💨", "Use the blow dryer to dry your hair.", "用吹風機把頭髮吹乾。"),
        ("hairbrush", "梳子（髮刷）", "n.", "💇", "I can't find my hairbrush.", "我找不到我的髮刷。"),
        ("toothpaste", "牙膏", "n.", "🪥", "Put a little toothpaste on the brush.", "在牙刷上擠一點牙膏。"),
        ("nail polish", "指甲油", "n.", "💅", "Her nail polish is pink.", "她的指甲油是粉紅色的。"),
        ("electric razor", "電動刮鬍刀", "n.", "🪒", "My brother has a new electric razor.", "我哥哥有一把新的電動刮鬍刀。"),
        ("cotton swab", "棉花棒", "n.", "🧻", "Don't push a cotton swab deep into your ear.", "不要把棉花棒伸進耳朵太深。"),
        ("shampoo", "洗髮精", "n.", "🧴", "This shampoo smells like apples.", "這瓶洗髮精聞起來像蘋果。"),
        ("conditioner", "潤髮乳", "n.", "🧴", "Use conditioner after you use shampoo.", "用完洗髮精後再用潤髮乳。"),
        ("scale", "體重計", "n.", "⚖️", "Step on the scale to check your weight.", "站上體重計量體重。"),
        ("compact", "粉盒（隨身化妝鏡盒）", "n.", "🪞", "She checked her face in a compact.", "她用粉盒鏡子看了一下自己的臉。"),
        ("nail clipper", "指甲刀", "n.", "✂️", "Please give me the nail clipper.", "請把指甲刀拿給我。"),
        ("toothbrush", "牙刷", "n.", "🪥", "Change your toothbrush every three months.", "牙刷每三個月要換一支。"),
        ("razor blade", "刮鬍刀片", "n.", "🪒", "Be careful with the razor blade.", "小心使用刮鬍刀片。"),
        ("mascara", "睫毛膏", "n.", "👁️", "She put mascara on her eyelashes.", "她在睫毛上刷了睫毛膏。"),
        ("laundry basket", "洗衣籃", "n.", "🧺", "Put your dirty socks in the laundry basket.", "把髒襪子放進洗衣籃。"),
        ("robe", "浴袍", "n.", "🥋", "He put on a robe after his shower.", "他洗完澡後穿上浴袍。"),
    ],
    speakers=dict(
        M=dict(name="Sophie", zh="蘇菲", avatar="🙋‍♀️", voice="af_sarah"),
        B=dict(name="Sam", zh="山姆", avatar="🙋‍♂️", voice="am_michael"),
    ),
    dialogueTitle="一起去露營：打包盥洗用品",
    dialogue=[
        ("B", "Sophie, we leave for the camping trip tomorrow. Did you pack your things?", "蘇菲，我們明天要去露營了，你的東西打包好了嗎？"),
        ("M", "Almost. I have my toothbrush, toothpaste, and soap.", "差不多了。我帶了牙刷、牙膏和肥皂。"),
        ("B", "Don't forget shampoo and conditioner. Oh, and a hairbrush!", "別忘了洗髮精和潤髮乳。喔，還有梳子！"),
        ("M", "I won't take a blow dryer. There's no electricity at the campsite.", "我不會帶吹風機，營地沒有電。"),
        ("B", "Good point. I'll leave my electric razor at home, too. I'll bring a razor and a few razor blades.", "有道理。我也把電動刮鬍刀留在家裡，帶一把刮鬍刀和幾片刀片就好。"),
        ("M", "Be careful with the razor blades. Put them in a small box.", "刀片要小心，放進一個小盒子裡。"),
        ("B", "Okay. Do you need a nail clipper? Mine is in the bathroom.", "好。你需要指甲刀嗎？我的在浴室裡。"),
        ("M", "Yes, please. And a cotton swab for my ears.", "要，麻煩你。還要一根棉花棒清耳朵。"),
        ("B", "Will you wear lipstick or nail polish in the forest?", "你在森林裡會擦口紅或指甲油嗎？"),
        ("M", "No way! I'll leave the lipstick, mascara, and compact at home.", "才不會！口紅、睫毛膏和粉盒我都留在家裡。"),
        ("B", "Smart. Put the dirty clothes in the laundry basket when we get back.", "聰明。回來之後把髒衣服放進洗衣籃。"),
        ("M", "Sure. I'll also bring a robe for the cold nights. Is the scale in the car? Mom wants to weigh the bags.", "好。我還會帶一件浴袍禦寒。體重計在車上嗎？媽媽想秤行李重量。"),
    ],
)
