TOPIC = dict(
    id="home-3", cat="home", catZh="居家", catEn="Around the House",
    title="客廳（二）", titleEn="In a living room, too", emoji="🛋️",
    words=[
        ("lighter", "打火機", "n.", "🔥", "Never play with a lighter.", "千萬不要玩打火機。"),
        ("matches", "火柴", "n.", "🔥", "Keep the matches away from children.", "火柴要放在小孩拿不到的地方。"),
        ("waste basket", "垃圾桶（室內小型）", "n.", "🗑️", "Throw the paper into the waste basket.", "把紙丟進垃圾桶。"),
        ("armchair", "扶手椅", "n.", "💺", "Dad reads the newspaper in his armchair.", "爸爸坐在扶手椅上看報紙。"),
        ("end table", "沙發邊桌", "n.", "🪑", "There is a lamp on the end table.", "邊桌上有一盞檯燈。"),
        ("telephone", "電話", "n.", "☎️", "The telephone is ringing.", "電話在響。"),
        ("vacuum cleaner", "吸塵器", "n.", "🧹", "I use the vacuum cleaner on Sundays.", "我每個星期天都用吸塵器。"),
        ("recliner", "躺椅（可調整靠背）", "n.", "🛋️", "Grandpa leans back in the recliner.", "爺爺往後靠在躺椅上。"),
        ("rocking chair", "搖椅", "n.", "🪑", "Grandma sits in the rocking chair and knits.", "奶奶坐在搖椅上織毛線。"),
        ("air conditioner", "冷氣機", "n.", "❄️", "Turn on the air conditioner. It's so hot.", "把冷氣打開，好熱喔。"),
        ("vase", "花瓶", "n.", "🏺", "She put some roses in the vase.", "她把幾朵玫瑰花插進花瓶。"),
    ],
    speakers=dict(
        M=dict(name="Amy", zh="艾咪", avatar="🙋‍♀️", voice="af_sarah"),
        B=dict(name="Jack", zh="傑克", avatar="🙋‍♂️", voice="am_michael"),
    ),
    dialogueTitle="夏天的下午：家裡好熱",
    dialogue=[
        ("M", "Jack, it's so hot in here. Can you turn on the air conditioner?", "傑克，這裡好熱。你可以把冷氣打開嗎？"),
        ("B", "Sure. The remote is on the end table next to the armchair.", "好啊。遙控器在扶手椅旁邊的邊桌上。"),
        ("M", "Thanks. Oh, the telephone is ringing!", "謝謝。喔，電話在響！"),
        ("B", "It's Grandma. She wants to know if we need anything.", "是奶奶打來的。她想知道我們需不需要什麼。"),
        ("M", "Tell her we're fine. Grandpa is in the recliner, and I'm in the rocking chair.", "告訴她我們都很好。爺爺在躺椅上，我坐在搖椅上。"),
        ("B", "Wait. Why is there paper on the floor?", "等一下，地板上怎麼有紙？"),
        ("M", "Sorry, I missed the waste basket. I'll pick it up.", "抱歉，我沒丟進垃圾桶。我來撿。"),
        ("B", "Please use the vacuum cleaner too. There are crumbs everywhere.", "也請用吸塵器吸一下，到處都是碎屑。"),
        ("M", "Okay. Do you know where the matches are? Mom wants to light the candles.", "好。你知道火柴在哪裡嗎？媽媽想點蠟燭。"),
        ("B", "They are in the drawer, but ask Mom to use the lighter. It's safer.", "在抽屜裡，不過請媽媽用打火機，比較安全。"),
        ("M", "All right. Look at the vase! Dad bought fresh flowers.", "好。你看那個花瓶！爸爸買了新鮮的花。"),
        ("B", "They look beautiful. Now the room is cool, clean, and pretty.", "好漂亮。現在房間又涼又乾淨又好看。"),
    ],
)
