TOPIC = dict(
    id="home-2", cat="home", catZh="居家", catEn="Around the House",
    title="客廳（一）", titleEn="In a living room", emoji="🛋️",
    words=[
        ("ceiling", "天花板", "n.", "🏠", "There is a fan on the ceiling.", "天花板上有一台電風扇。"),
        ("wall", "牆壁", "n.", "🧱", "We painted the wall light blue.", "我們把牆壁漆成淺藍色。"),
        ("clock", "時鐘", "n.", "🕰️", "The clock says seven o'clock.", "時鐘顯示七點整。"),
        ("painting", "畫（掛在牆上的）", "n.", "🖼️", "She hung a painting above the sofa.", "她在沙發上方掛了一幅畫。"),
        ("television", "電視機", "n.", "📺", "The television is too loud.", "電視機太大聲了。"),
        ("TV stand", "電視櫃", "n.", "🗄️", "The game console is on the TV stand.", "遊戲機放在電視櫃上。"),
        ("bookcase", "書櫃", "n.", "📚", "My comic books are in the bookcase.", "我的漫畫書放在書櫃裡。"),
        ("floor lamp", "落地燈", "n.", "💡", "Turn on the floor lamp, please.", "請把落地燈打開。"),
        ("hardwood floor", "木質地板", "n.", "🪵", "Take off your shoes on the hardwood floor.", "在木質地板上要脫鞋。"),
        ("rug", "小地毯", "n.", "🟫", "The cat sleeps on the rug.", "貓睡在小地毯上。"),
        ("headphones", "耳機", "n.", "🎧", "He wears headphones when he studies.", "他念書時會戴耳機。"),
        ("coffee table", "茶几", "n.", "☕", "Put the snacks on the coffee table.", "把點心放在茶几上。"),
        ("throw pillow", "抱枕", "n.", "🛏️", "I hug a throw pillow when I watch movies.", "我看電影時會抱著抱枕。"),
        ("sofa", "沙發", "n.", "🛋️", "Grandpa is taking a nap on the sofa.", "爺爺正在沙發上小睡。"),
        ("chair", "椅子", "n.", "🪑", "Please pull up a chair and sit down.", "請拉一張椅子坐下。"),
        ("calendar", "月曆", "n.", "📅", "Mark the party on the calendar.", "把派對標在月曆上。"),
        ("light switch", "電燈開關", "n.", "🔘", "The light switch is next to the door.", "電燈開關在門旁邊。"),
        ("door", "門", "n.", "🚪", "Please close the door quietly.", "請輕輕把門關上。"),
    ],
    speakers=dict(
        M=dict(name="Lily", zh="莉莉", avatar="🙋‍♀️", voice="af_sarah"),
        B=dict(name="Tom", zh="湯姆", avatar="🙋‍♂️", voice="am_michael"),
    ),
    dialogueTitle="週末大掃除：整理客廳",
    dialogue=[
        ("B", "Lily, let's clean the living room before Grandma comes.", "莉莉，我們在奶奶來之前把客廳整理一下吧。"),
        ("M", "Okay. First, I'll dust the bookcase and the TV stand.", "好。我先把書櫃和電視櫃擦乾淨。"),
        ("B", "I'll clean the coffee table and put the throw pillows back on the sofa.", "我來擦茶几，再把抱枕放回沙發上。"),
        ("M", "Wow, there are headphones under the chair!", "哇，椅子下面有一副耳機！"),
        ("B", "Oh, those are mine. I was looking for them all week.", "喔，那是我的。我找了一整個星期。"),
        ("M", "Can you move the rug? I want to sweep the hardwood floor.", "你可以把小地毯移開嗎？我想掃一下木地板。"),
        ("B", "Sure. Look, the wall behind it is really dirty.", "好啊。你看，後面的牆壁真的很髒。"),
        ("M", "We can hang a painting there. That will look nicer.", "我們可以在那裡掛一幅畫，那樣會比較好看。"),
        ("B", "Good idea. What time is it now? The clock stopped again.", "好主意。現在幾點了？時鐘又停了。"),
        ("M", "It's three o'clock. Grandma will be here at four.", "三點了。奶奶四點會到。"),
        ("B", "Let's check the calendar. Is she staying for two days or three?", "我們來看一下月曆，她是住兩天還是三天？"),
        ("M", "Two days. Now turn on the floor lamp, and the room looks perfect!", "兩天。現在把落地燈打開，房間就完美了！"),
    ],
)
