TOPIC = dict(
    id="home-7", cat="home", catZh="居家", catEn="Around the House",
    title="洗衣與縫紉", titleEn="In a basement", emoji="🧺",
    words=[
        ("detergent", "洗衣精（清潔劑）", "n.", "🧴", "Add a little detergent to the washer.", "在洗衣機裡加一點洗衣精。"),
        ("fabric softener", "衣物柔軟精", "n.", "🧴", "Fabric softener makes clothes soft.", "柔軟精讓衣服變得柔軟。"),
        ("bleach", "漂白水", "n.", "🧪", "Don't use bleach on colored clothes.", "彩色衣服不要用漂白水。"),
        ("sewing machine", "縫紉機", "n.", "🧵", "Grandma makes dresses with a sewing machine.", "奶奶用縫紉機做洋裝。"),
        ("hanger", "衣架", "n.", "🧥", "Hang your coat on a hanger.", "把外套掛在衣架上。"),
        ("safety pin", "別針", "n.", "📌", "She fixed the button with a safety pin.", "她用別針固定住鈕扣。"),
        ("needle", "縫衣針", "n.", "🪡", "Be careful with the needle.", "使用縫衣針要小心。"),
        ("cloth", "布料", "n.", "🧶", "This cloth is soft and cheap.", "這塊布料又軟又便宜。"),
        ("clothes pin", "曬衣夾", "n.", "📎", "Use clothes pins to hold the shirts.", "用曬衣夾夾住襯衫。"),
        ("thread", "縫線", "n.", "🧵", "I need red thread for the button.", "我需要紅色的線縫鈕扣。"),
        ("scissors", "剪刀", "n.", "✂️", "Cut the cloth with scissors.", "用剪刀剪布。"),
        ("ironing board", "燙衣板", "n.", "🧺", "Put the shirt on the ironing board.", "把襯衫放在燙衣板上。"),
        ("iron", "熨斗", "n.", "♨️", "The iron is very hot.", "熨斗很燙。"),
        ("yarn", "毛線", "n.", "🧶", "She is knitting a scarf with blue yarn.", "她正在用藍色毛線織圍巾。"),
        ("dryer", "烘衣機", "n.", "🌀", "Put the towels in the dryer.", "把毛巾放進烘衣機。"),
        ("washing machine", "洗衣機", "n.", "🧺", "The washing machine is in the basement.", "洗衣機放在地下室。"),
    ],
    speakers=dict(
        M=dict(name="Nina", zh="妮娜", avatar="🙋‍♀️", voice="af_sarah"),
        B=dict(name="Mom", zh="媽媽", avatar="👩", voice="af_heart"),
    ),
    dialogueTitle="地下室的洗衣日",
    dialogue=[
        ("M", "Mom, my school shirt has a hole. Can you help me fix it?", "媽媽，我的學校襯衫破了一個洞，你可以幫我補嗎？"),
        ("B", "Sure. Go to the basement and get the sewing machine and a needle.", "好啊。去地下室把縫紉機和一支針拿來。"),
        ("M", "Do we have thread the same color as the shirt?", "我們有跟襯衫同顏色的線嗎？"),
        ("B", "Look in the box. There's white thread next to the scissors.", "看看盒子裡，剪刀旁邊有白色的線。"),
        ("M", "I found it. Can I also use a safety pin to hold the cloth?", "我找到了。我可以用別針把布固定住嗎？"),
        ("B", "Yes. After that, we'll wash the other clothes. Put the detergent in the washing machine.", "可以。之後我們來洗其他衣服。把洗衣精倒進洗衣機。"),
        ("M", "Should I use bleach for the white socks?", "白襪子要用漂白水嗎？"),
        ("B", "A little. And add fabric softener at the end, so they feel soft.", "一點點就好。最後再加柔軟精，穿起來才會軟。"),
        ("M", "Then I'll put them in the dryer. What about the wool sweater?", "那我把它們放進烘衣機。毛衣怎麼辦？"),
        ("B", "Don't dry it. Hang it on a hanger, or hold it with clothes pins outside.", "毛衣不要烘乾。用衣架掛起來，或用曬衣夾夾在外面。"),
        ("M", "Okay. I'll also set up the ironing board for your blouse.", "好。我也會把燙衣板拿出來燙你的上衣。"),
        ("B", "Thanks, Nina. Be careful with the iron, and leave the yarn on the shelf for my scarf.", "謝謝你，妮娜。小心熨斗，毛線留在架子上，我要織圍巾。"),
    ],
)
