TOPIC = dict(
    id="home-4", cat="home", catZh="居家", catEn="Around the House",
    title="浴室", titleEn="In a bathroom", emoji="🛁",
    words=[
        ("tile", "磁磚", "n.", "🟦", "The bathroom floor is covered with white tile.", "浴室的地板鋪著白色磁磚。"),
        ("bath towel", "浴巾", "n.", "🧖", "Grab a clean bath towel from the shelf.", "從架子上拿一條乾淨的浴巾。"),
        ("bathroom shelves", "浴室置物架", "n.", "🗄️", "The soap is on the bathroom shelves.", "肥皂放在浴室置物架上。"),
        ("mirror", "鏡子", "n.", "🪞", "He looks at himself in the mirror.", "他看著鏡子裡的自己。"),
        ("washcloth", "洗臉小毛巾", "n.", "🧼", "Wet the washcloth and wash your face.", "把小毛巾弄濕，然後洗臉。"),
        ("sink", "洗手台", "n.", "🚰", "Wash your hands in the sink.", "在洗手台洗手。"),
        ("faucet", "水龍頭", "n.", "🚰", "Don't forget to turn off the faucet.", "別忘了關水龍頭。"),
        ("toilet paper", "衛生紙", "n.", "🧻", "We need to buy more toilet paper.", "我們要再多買一點衛生紙。"),
        ("drain", "排水孔", "n.", "🕳️", "Hair is stuck in the drain.", "頭髮卡在排水孔裡。"),
        ("toilet tank", "馬桶水箱", "n.", "🚽", "The toilet tank is leaking.", "馬桶水箱在漏水。"),
        ("toilet", "馬桶", "n.", "🚽", "Please flush the toilet.", "請沖馬桶。"),
        ("bath mat", "浴室防滑墊", "n.", "🟩", "Step on the bath mat to dry your feet.", "踩在防滑墊上把腳擦乾。"),
        ("shower curtain", "浴簾", "n.", "🚿", "Pull the shower curtain closed.", "把浴簾拉上。"),
        ("shower head", "蓮蓬頭", "n.", "🚿", "The shower head is too high for me.", "蓮蓬頭對我來說太高了。"),
        ("bathtub", "浴缸", "n.", "🛁", "The baby plays with toys in the bathtub.", "寶寶在浴缸裡玩玩具。"),
    ],
    speakers=dict(
        M=dict(name="Emma", zh="艾瑪", avatar="🙋‍♀️", voice="af_sarah"),
        B=dict(name="Dad", zh="爸爸", avatar="👨", voice="am_michael"),
    ),
    dialogueTitle="浴室壞掉了：爸爸的修理時間",
    dialogue=[
        ("M", "Dad, there is water on the bathroom floor!", "爸爸，浴室地板上有水！"),
        ("B", "Let me see. Hmm, the faucet is dripping, and the toilet tank is leaking too.", "我看看。嗯，水龍頭在滴水，馬桶水箱也在漏水。"),
        ("M", "Can you fix them? I need to take a shower.", "你可以修理嗎？我要洗澡。"),
        ("B", "Of course. First, put the bath mat in the hall so it stays dry.", "當然。先把防滑墊拿到走廊，才不會弄濕。"),
        ("M", "Okay. The shower curtain is wet, too. Should I hang it outside?", "好。浴簾也濕了，我要把它掛到外面嗎？"),
        ("B", "Yes. And take the bath towel and washcloth away from the shelves.", "要。還要把浴巾和小毛巾從置物架上拿走。"),
        ("M", "Why is the sink full of water?", "為什麼洗手台裡都是水？"),
        ("B", "Something is stuck in the drain. I'll clean it now.", "排水孔裡有東西卡住了，我現在來清。"),
        ("M", "Dad, look at the tile. It's so slippery!", "爸爸你看磁磚，好滑喔！"),
        ("B", "Be careful. Don't go near the bathtub until I'm done.", "小心，我弄好之前不要靠近浴缸。"),
        ("M", "Okay. Could you check the shower head too? The water is cold.", "好。你可以也看一下蓮蓬頭嗎？水是冷的。"),
        ("B", "I will. After that, I'll buy new toilet paper and a clean mirror cloth.", "我會的。之後我會去買新的衛生紙和擦鏡子的布。"),
    ],
)
