TOPIC = dict(
    id="home-10", cat="home", catZh="居家", catEn="Around the House",
    title="工具", titleEn="Tools", emoji="🔧",
    words=[
        ("tape", "膠帶", "n.", "📼", "Fix the poster with tape.", "用膠帶把海報貼好。"),
        ("hammer", "鐵鎚", "n.", "🔨", "He hit the nail with a hammer.", "他用鐵鎚敲釘子。"),
        ("fluorescent light", "日光燈", "n.", "💡", "The fluorescent light is too bright.", "日光燈太亮了。"),
        ("electric drill", "電鑽", "n.", "🔩", "Dad made a hole with an electric drill.", "爸爸用電鑽鑽了一個洞。"),
        ("paint roller", "油漆滾筒", "n.", "🎨", "Use a paint roller to paint the wall.", "用油漆滾筒粉刷牆壁。"),
        ("screwdriver", "螺絲起子", "n.", "🪛", "Turn the screw with a screwdriver.", "用螺絲起子轉螺絲。"),
        ("pliers", "鉗子", "n.", "🔧", "Pull out the nail with pliers.", "用鉗子把釘子拔出來。"),
        ("scrubbing brush", "刷子（刷洗用）", "n.", "🧽", "Scrub the floor with a scrubbing brush.", "用刷子刷洗地板。"),
        ("paint brush", "油漆刷", "n.", "🖌️", "She painted the door with a paint brush.", "她用油漆刷漆門。"),
        ("axe", "斧頭", "n.", "🪓", "He cut the wood with an axe.", "他用斧頭劈木頭。"),
        ("tape measure", "捲尺", "n.", "📏", "Use a tape measure to measure the table.", "用捲尺量桌子。"),
        ("hinge", "鉸鍊（門的）", "n.", "🚪", "The door hinge is rusty.", "門的鉸鍊生鏽了。"),
        ("toolbox", "工具箱", "n.", "🧰", "Dad keeps the tools in a toolbox.", "爸爸把工具放在工具箱裡。"),
        ("flashlight", "手電筒", "n.", "🔦", "Take a flashlight when you go camping.", "去露營要帶手電筒。"),
        ("nail", "釘子", "n.", "📍", "There is a nail in the wall.", "牆上有一根釘子。"),
        ("shovel", "鏟子", "n.", "⛏️", "He dug a hole with a shovel.", "他用鏟子挖了一個洞。"),
        ("paint", "油漆", "n.", "🪣", "We need two buckets of white paint.", "我們需要兩桶白色油漆。"),
        ("ladder", "梯子", "n.", "🪜", "Climb the ladder slowly.", "慢慢爬上梯子。"),
        ("bucket", "水桶", "n.", "🪣", "Fill the bucket with water.", "把水桶裝滿水。"),
        ("sponge", "海綿", "n.", "🧽", "Wipe the table with a wet sponge.", "用濕海綿擦桌子。"),
    ],
    speakers=dict(
        M=dict(name="Jenny", zh="珍妮", avatar="🙋‍♀️", voice="af_sarah"),
        B=dict(name="Uncle Ray", zh="雷叔叔", avatar="👨", voice="am_adam"),
    ),
    dialogueTitle="幫雷叔叔粉刷小倉庫",
    dialogue=[
        ("B", "Jenny, thanks for helping me paint the shed today.", "珍妮，謝謝你今天幫我粉刷小倉庫。"),
        ("M", "No problem, Uncle Ray. Where is your toolbox?", "沒問題，雷叔叔。你的工具箱在哪裡？"),
        ("B", "It's by the door. Please take out the screwdriver and the pliers.", "在門邊。請把螺絲起子和鉗子拿出來。"),
        ("M", "Got them. The door hinge is loose. Should I use the electric drill?", "拿到了。門的鉸鍊鬆了，我要用電鑽嗎？"),
        ("B", "Yes, but wear your glasses. I'll bring the ladder.", "要，不過要戴眼鏡。我去拿梯子。"),
        ("M", "I'll measure the wall with the tape measure first.", "我先用捲尺量一下牆。"),
        ("B", "Good. Then open the paint and use the paint roller for the big wall.", "好。然後打開油漆，大面牆用滾筒刷。"),
        ("M", "What about the corners? Can I use a paint brush?", "角落呢？可以用油漆刷嗎？"),
        ("B", "Of course. Put the tape on the window first, so it stays clean.", "當然可以。先在窗戶上貼膠帶，才不會弄髒。"),
        ("M", "It's getting dark in here. Where is the flashlight?", "這裡越來越暗了，手電筒在哪裡？"),
        ("B", "Next to the shovel, and turn on the fluorescent light, too.", "在鏟子旁邊，也順便把日光燈打開。"),
        ("M", "Okay. When we finish, I'll wash the brushes in the bucket with a sponge and put the hammer, nails, and axe back.", "好。做完之後，我會在水桶裡用海綿洗刷子，再把鐵鎚、釘子和斧頭放回去。"),
    ],
)
