TOPIC = dict(
    id="home-9", cat="home", catZh="居家", catEn="Around the House",
    title="廚房用具", titleEn="Kitchenware", emoji="🥄",
    words=[
        ("corkscrew", "開瓶器（軟木塞用）", "n.", "🍾", "Use a corkscrew to open the wine.", "用開瓶器打開紅酒。"),
        ("spatula turner", "鍋鏟", "n.", "🍳", "Turn the pancake with a spatula turner.", "用鍋鏟把鬆餅翻面。"),
        ("rolling pin", "擀麵棍", "n.", "🥖", "Roll the dough flat with a rolling pin.", "用擀麵棍把麵糰擀平。"),
        ("teapot", "茶壺", "n.", "🫖", "Grandma pours tea from the teapot.", "奶奶從茶壺倒茶。"),
        ("hot mitt", "隔熱手套", "n.", "🧤", "Wear a hot mitt to take out the pie.", "戴上隔熱手套把派拿出來。"),
        ("mug", "馬克杯", "n.", "☕", "I drink hot chocolate from my favorite mug.", "我用最喜歡的馬克杯喝熱巧克力。"),
        ("two-pronged fork", "雙叉燒烤叉（兩齒叉）", "n.", "🍴", "Pick up the meat with a two-pronged fork.", "用雙叉把肉夾起來。"),
        ("whisk", "打蛋器", "n.", "🥚", "Beat the eggs with a whisk.", "用打蛋器打蛋。"),
        ("dish soap", "洗碗精", "n.", "🧴", "Add some dish soap to the water.", "在水裡加一點洗碗精。"),
        ("bottle opener", "開瓶蓋器", "n.", "🍺", "I need a bottle opener for this soda.", "這瓶汽水需要開瓶蓋器。"),
        ("aluminum foil", "鋁箔紙", "n.", "🪩", "Wrap the potato in aluminum foil.", "把馬鈴薯用鋁箔紙包起來。"),
        ("cup", "杯子", "n.", "🥛", "She filled the cup with milk.", "她把杯子裝滿牛奶。"),
        ("scouring pad", "菜瓜布（刷鍋用的）", "n.", "🧽", "Scrub the pot with a scouring pad.", "用菜瓜布刷鍋子。"),
        ("plastic wrap", "保鮮膜", "n.", "🎞️", "Cover the bowl with plastic wrap.", "用保鮮膜把碗蓋起來。"),
        ("hot pad", "隔熱墊", "n.", "🟫", "Put the hot pot on the hot pad.", "把熱鍋放在隔熱墊上。"),
        ("rice spatula", "飯勺", "n.", "🥄", "Use the rice spatula to serve the rice.", "用飯勺盛飯。"),
        ("can opener", "開罐器", "n.", "🥫", "Open the can with a can opener.", "用開罐器打開罐頭。"),
        ("potato peeler", "削皮器", "n.", "🥔", "He peeled the potatoes with a potato peeler.", "他用削皮器削馬鈴薯皮。"),
    ],
    speakers=dict(
        M=dict(name="Ella", zh="艾拉", avatar="🙋‍♀️", voice="af_sarah"),
        B=dict(name="Chris", zh="克里斯", avatar="🙋‍♂️", voice="am_michael"),
    ),
    dialogueTitle="烘焙社團：做馬鈴薯鬆餅",
    dialogue=[
        ("B", "Ella, today our baking club is making potato pancakes.", "艾拉，今天烘焙社要做馬鈴薯鬆餅。"),
        ("M", "Yum! What do we need?", "好好吃的樣子！我們需要什麼？"),
        ("B", "A potato peeler, a whisk, a spatula turner, and a pan.", "削皮器、打蛋器、鍋鏟，還有平底鍋。"),
        ("M", "I'll peel the potatoes first. Can you pass me the can opener? I want to open the corn, too.", "我先削馬鈴薯皮。你可以把開罐器拿給我嗎？我也想打開玉米罐頭。"),
        ("B", "Here. I'll beat the eggs with the whisk.", "給你。我用打蛋器打蛋。"),
        ("M", "Do we need the rolling pin?", "我們需要擀麵棍嗎？"),
        ("B", "No, that's for pizza dough next week. Now fry them with the spatula turner.", "不用，那是下週做披薩麵糰用的。現在用鍋鏟煎它們。"),
        ("M", "Put on the hot mitt, and move the hot pan onto the hot pad.", "戴上隔熱手套，把熱鍋移到隔熱墊上。"),
        ("B", "Got it. Let's wrap the leftovers in aluminum foil or plastic wrap.", "知道了。剩下的用鋁箔紙或保鮮膜包起來吧。"),
        ("M", "Great. And I'll make tea in the teapot. Who wants a mug?", "好。我來用茶壺泡茶，誰要馬克杯？"),
        ("B", "Me! Do you have a cup for the juice too?", "我要！你也有裝果汁的杯子嗎？"),
        ("M", "Yes. After lunch, we'll wash everything with dish soap and a scouring pad.", "有。午餐後，我們會用洗碗精和菜瓜布把所有東西洗乾淨。"),
    ],
)
